/**
 * HTML sanitization utility for markdown output.
 *
 * Uses sanitize-html with a whitelist approach to allow only the HTML elements
 * and attributes that marked legitimately generates. This protects against XSS
 * attacks from user-supplied or AI-generated markdown content while preserving
 * all expected formatting (mermaid diagrams, GFM Alerts, task lists, tables, etc.).
 */

import sanitizeHtml from "sanitize-html";

/**
 * Tags that marked (with our extensions) can legitimately produce.
 * Dangerous tags like script, style, iframe, object, embed are intentionally excluded.
 */
const ALLOWED_TAGS: string[] = [
  // Block elements
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "blockquote",
  "pre",
  "hr",
  "br",
  "table",
  "thead",
  "tbody",
  "tr",
  "th",
  "td",
  // Inline elements
  "a",
  "strong",
  "em",
  "code",
  "del",
  "img",
  // GFM task list checkbox
  "input",
  // Structural elements used by mermaid extension and GFM Alerts
  "div",
  "span",
  "section",
  "details",
  "summary",
  // SVG icons used by marked-alert for GFM Alert admonitions (> [!NOTE], etc.)
  "svg",
  "path",
];

/**
 * Allowed attributes per tag. Only the attributes that marked and our
 * extensions actually produce are permitted. Event handler attributes (on*)
 * are blocked by sanitize-html's default behavior.
 */
const ALLOWED_ATTRIBUTES: Record<string, sanitizeHtml.AllowedAttribute[]> = {
  a: ["href", "title", "target", "rel"],
  img: ["src", "alt", "title", "width", "height"],
  // Heading IDs generated by our heading extension
  h1: ["id"],
  h2: ["id"],
  h3: ["id"],
  h4: ["id"],
  h5: ["id"],
  h6: ["id"],
  // GFM task list checkboxes: marked generates <input checked="" disabled="" type="checkbox">
  input: ["type", "checked", "disabled"],
  // GFM Alert title paragraph uses class="markdown-alert-title"
  p: ["class"],
  // mermaid extension uses <div class="mermaid">, GFM Alerts use class attributes
  div: ["class"],
  span: ["class"],
  section: ["class"],
  // SVG elements in GFM Alert icons
  svg: ["class", "viewBox", "width", "height", "aria-hidden"],
  path: ["d"],
  // Code blocks can have class for language hints (e.g., class="language-js")
  code: ["class"],
  // Table alignment
  td: ["align", "style"],
  th: ["align", "style"],
};

/**
 * Sanitize HTML output from marked to prevent XSS attacks.
 *
 * Allows only the tags, attributes, and URL schemes that marked with our
 * extensions legitimately produces. Everything else is stripped.
 *
 * @param html - Raw HTML string from marked
 * @returns Sanitized HTML string safe for dangerouslySetInnerHTML
 */
export function sanitize(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: ALLOWED_ATTRIBUTES,
    // Only allow safe URL schemes for links and images.
    // This blocks javascript:, data:, and vbscript: protocols that can be used for XSS.
    allowedSchemes: ["http", "https", "mailto"],
    allowedSchemesByTag: {
      a: ["http", "https", "mailto"],
      img: ["http", "https"],
    },
    // Preserve self-closing tags like <br />, <hr />, <img />
    selfClosing: ["br", "hr", "img", "input"],
    // Strip disallowed tags entirely (don't show their text content)
    disallowedTagsMode: "discard",
    // Allow only safe CSS properties for table cell alignment
    allowedStyles: {
      td: { "text-align": [/^(left|center|right)$/] },
      th: { "text-align": [/^(left|center|right)$/] },
    },
  });
}
