// Writes the mode-dependent generated files into the site copy: src/app/fonts-generated.css and src/lib/fontmode.json
// usage: DISPLAY=swap|optional|block INLINE=0|1 FACE=p|ud LATIN_DISPLAY=(defaults to DISPLAY) node prep.mjs
import fs from "node:fs";
const S = "/home/user/yolo-web/tmp/t1a3/site/";
const DISPLAY = process.env.DISPLAY || "swap", INLINE = process.env.INLINE === "1", FACE = process.env.FACE || "p";
const PRELOAD = process.env.PRELOAD || "div";
const LATIN_DISPLAY = process.env.LATIN_DISPLAY || DISPLAY;
const man = JSON.parse(fs.readFileSync(S + "fontbuild/manifest.json", "utf8"))[FACE];
const ch = man.__chrome;
const src = (f) => INLINE ? `url(data:font/woff2;base64,${fs.readFileSync(S + "public/__pf/" + f).toString("base64")})` : `url(/__pf/${f})`;
const MINCHO = `"Hiragino Mincho ProN","Yu Mincho",serif`;
const GOTHIC = `"Hiragino Kaku Gothic ProN","Yu Gothic Medium","Noto Sans JP","IPAGothic",sans-serif`;
const LFB = `"Yolos Sans Fallback"`;
const css = `
/* generated by tmp/t1a3/work/prep.mjs: DISPLAY=${DISPLAY} LATIN_DISPLAY=${LATIN_DISPLAY} INLINE=${INLINE} FACE=${FACE} */
@font-face{font-family:"Yolos Sans";font-weight:400;font-display:${LATIN_DISPLAY};src:url(/__pf/yolos-sans-400.woff2) format("woff2");unicode-range:U+0020-007E}
@font-face{font-family:"Yolos Sans";font-weight:700;font-display:${LATIN_DISPLAY};src:url(/__pf/yolos-sans-700.woff2) format("woff2");unicode-range:U+0020-007E}
@font-face{font-family:"Yolos Sans Fallback";font-weight:400;src:local("Arial"),local("ArialMT"),local("Liberation Sans"),local("LiberationSans"),local("Helvetica Neue"),local("Helvetica"),local("Roboto");size-adjust:100.2%;ascent-override:102.3%;descent-override:27.4%;line-gap-override:0%;unicode-range:U+0020-007E}
@font-face{font-family:"Yolos Sans Fallback";font-weight:700;src:local("Arial Bold"),local("Arial-BoldMT"),local("Liberation Sans Bold"),local("LiberationSans-Bold"),local("Helvetica Neue Bold"),local("Helvetica Bold"),local("Roboto Bold");size-adjust:98.3%;ascent-override:104.3%;descent-override:28%;line-gap-override:0%;unicode-range:U+0020-007E}
@font-face{font-family:"yc-h";font-weight:400;font-display:${DISPLAY};src:url(/__pf/${ch.zen.file}) format("woff2")}
@font-face{font-family:"yc";font-weight:400;font-display:${DISPLAY};src:url(/__pf/${ch.biz400.file}) format("woff2")}
:root{--font-mincho:"Yolos Sans",${LFB},${MINCHO};--font-gothic:"Yolos Sans",${LFB},${GOTHIC};--font-number:"Yolos Sans",${LFB},${GOTHIC}}
body>header,body>footer,body>a{--font-mincho:"Yolos Sans","yc-h",${LFB},${MINCHO};--font-gothic:"Yolos Sans","yc",${LFB},${GOTHIC};--font-number:"Yolos Sans","yc",${LFB},${GOTHIC};font-family:var(--font-gothic)}
input,textarea{font-family:"Yolos Sans",${LFB},${GOTHIC}}
button,select{font-family:inherit}
html{font-synthesis-weight:none}
h1,h2,h3,h4,h5,h6{font-weight:400}
${process.env.ADOPT === "1" ? "h1,h2,h3,h4,h5,h6{font-feature-settings:normal}body{text-spacing-trim:space-all}" : ""}
`;
fs.writeFileSync(S + "src/app/fonts-generated.css", css);
fs.writeFileSync(S + "src/lib/fontmode.json", JSON.stringify({ DISPLAY, INLINE, FACE, PRELOAD, chrome: [ch.zen.file, ch.biz400.file] }));
const links = {};
for (const [k, e] of Object.entries(man)) { if (k === "__chrome") continue; links[encodeURI(k)] = [e.page.zen, e.page.biz400, e.page.biz700].filter(Boolean).map((f) => f.file).concat(e.q ? [e.q.zen, e.q.biz400].filter(Boolean).map((f) => f.file + "|low") : []); }
links.__shared = ["yolos-sans-400.woff2", "yolos-sans-700.woff2", ch.zen.file, ch.biz400.file];
fs.writeFileSync(S + "src/lib/fontlinks.json", JSON.stringify(PRELOAD === "header" ? links : { __shared: [] }));
console.log("prepared", { PRELOAD, DISPLAY, LATIN_DISPLAY, INLINE, FACE });
