/**
 * Thin re-export from the auto-generated registry.
 *
 * The source of truth is src/cheatsheets/generated/cheatsheets-registry.ts,
 * which is regenerated by: npm run generate:toolbox-registry
 *
 * Do NOT add manual imports here. Add a meta.ts file under
 * src/cheatsheets/{slug}/ and run generate:toolbox-registry instead.
 */
export {
  cheatsheetsBySlug,
  allCheatsheetMetas,
  getAllCheatsheetSlugs,
} from "./generated/cheatsheets-registry";
