/**
 * Prebuild script: Generate content registries from individual meta.ts files.
 *
 * This script auto-discovers `meta.ts` files under `src/tools/` and `src/cheatsheets/`
 * and generates two files:
 *   1. `src/tools/generated/tools-registry.ts`          — tools-only registry (replaces hand-written)
 *   2. `src/cheatsheets/generated/cheatsheets-registry.ts` — cheatsheets-only registry (replaces hand-written)
 *
 * WHY codegen instead of hand-maintained central registry:
 * - Eliminates the class of bug where a developer adds `src/tools/new-tool/meta.ts`
 *   but forgets to register it in the registry.
 * - At 500+ entries scale, manual registration in a central file is error-prone.
 * - The `meta.ts` file IS the registration — no separate step needed.
 *
 * SCOPE:
 * - tools: `src/tools/{slug}/meta.ts` (named export `meta: ToolMeta`)
 * - cheatsheets: `src/cheatsheets/{slug}/meta.ts` (named export `meta: CheatsheetMeta`)
 *
 * CALLER COMPATIBILITY:
 * - `src/tools/registry.ts` re-exports from `src/tools/generated/tools-registry.ts`
 *   → callers (79 files) are unaffected; same export API (toolsBySlug, allToolMetas, getAllToolSlugs)
 * - `src/cheatsheets/registry.ts` re-exports from `src/cheatsheets/generated/cheatsheets-registry.ts`
 *   → callers (22 files) are unaffected; same export API (cheatsheetsBySlug, allCheatsheetMetas, getAllCheatsheetSlugs)
 *
 * OUTPUT files (all committed to git; lint/typecheck works without running prebuild):
 * - Regenerated on every prebuild/predev/pretest to stay in sync
 * - If manually edited, run `npm run generate:toolbox-registry` to revert.
 *   The git diff will show the unwanted edits, making them easy to detect and revert.
 */

import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";

const ROOT = path.resolve(process.cwd());
const TOOLS_OUTPUT_FILE = path.join(
  ROOT,
  "src/tools/generated/tools-registry.ts",
);
const CHEATSHEETS_OUTPUT_FILE = path.join(
  ROOT,
  "src/cheatsheets/generated/cheatsheets-registry.ts",
);

/** Extract slug from path like "src/tools/{slug}/meta.ts" */
function slugFromPath(filePath: string): string {
  const parts = filePath.split("/");
  // parts = ["src", "tools", "{slug}", "meta.ts"] → index -2 is slug
  return parts[parts.length - 2];
}

/**
 * 件数のサニティチェック。
 * glob の誤設定や予期しないディレクトリ構造変化で件数が激減した場合に早期エラーを出す。
 */
function assertMinCount(kind: string, actual: number, min: number): void {
  if (actual < min) {
    throw new Error(
      `[generate-toolbox-registry] SANITY CHECK FAILED: ` +
        `Expected at least ${min} ${kind} meta.ts files, but found ${actual}. ` +
        `Check src/${kind}/ directory structure.`,
    );
  }
}

/**
 * Generate the TypeScript source content for tools/generated/tools-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory.
 * This replaces the hand-written src/tools/registry.ts entry list.
 * The generated file is re-exported by src/tools/registry.ts to preserve
 * caller compatibility (toolsBySlug, allToolMetas, getAllToolSlugs).
 *
 * @param toolSlugs - sorted list of tool slugs discovered from src/tools/{slug}/meta.ts
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildToolsRegistryContent(toolSlugs: string[]): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-toolbox-registry.ts",
    " * Regenerate with: npm run generate:toolbox-registry",
    " *",
    " * This file is re-exported by src/tools/registry.ts.",
    " * Callers should import from src/tools/registry.ts, not this file.",
    " */",
    "",
    'import type { ToolMeta, ToolDefinition } from "@/tools/types";',
    "",
    "// --- Tool imports (auto-discovered from src/tools/{slug}/meta.ts) ---",
  ];

  for (const slug of toolSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`import { meta as ${importName} } from "@/tools/${slug}/meta";`);
  }

  lines.push("");
  lines.push("const toolEntries: ToolDefinition[] = [");
  for (const slug of toolSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`  { meta: ${importName} },`);
  }
  lines.push("];");
  lines.push("");
  lines.push("// Indexed by slug for O(1) lookup");
  lines.push(
    "export const toolsBySlug: Map<string, ToolDefinition> = new Map(",
  );
  lines.push("  toolEntries.map((entry) => [entry.meta.slug, entry]),");
  lines.push(");");
  lines.push("");
  lines.push("// All tool metadata (no component code loaded)");
  lines.push(
    "export const allToolMetas: ToolMeta[] = toolEntries.map((e) => e.meta);",
  );
  lines.push("");
  lines.push("// Get all tool slugs");
  lines.push("export function getAllToolSlugs(): string[] {");
  lines.push("  return toolEntries.map((e) => e.meta.slug);");
  lines.push("}");
  lines.push("");
  lines.push(`// Count at generation time: tools=${toolSlugs.length}`);

  return lines.join("\n");
}

/**
 * Generate the TypeScript source content for cheatsheets/generated/cheatsheets-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory.
 * This replaces the hand-written src/cheatsheets/registry.ts entry list.
 * The generated file is re-exported by src/cheatsheets/registry.ts to preserve
 * caller compatibility (cheatsheetsBySlug, allCheatsheetMetas, getAllCheatsheetSlugs).
 *
 * @param cheatsheetSlugs - sorted list of cheatsheet slugs from src/cheatsheets/{slug}/meta.ts
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildCheatsheetRegistryContent(
  cheatsheetSlugs: string[],
): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-toolbox-registry.ts",
    " * Regenerate with: npm run generate:toolbox-registry",
    " *",
    " * This file is re-exported by src/cheatsheets/registry.ts.",
    " * Callers should import from src/cheatsheets/registry.ts, not this file.",
    " */",
    "",
    'import type { CheatsheetMeta, CheatsheetDefinition } from "@/cheatsheets/types";',
    "",
    "// --- Cheatsheet imports (auto-discovered from src/cheatsheets/{slug}/meta.ts) ---",
  ];

  for (const slug of cheatsheetSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(
      `import { meta as ${importName} } from "@/cheatsheets/${slug}/meta";`,
    );
  }

  lines.push("");
  lines.push("const cheatsheetEntries: CheatsheetDefinition[] = [");
  for (const slug of cheatsheetSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`  { meta: ${importName} },`);
  }
  lines.push("];");
  lines.push("");
  lines.push(
    "export const cheatsheetsBySlug: Map<string, CheatsheetDefinition> = new Map(",
  );
  lines.push("  cheatsheetEntries.map((entry) => [entry.meta.slug, entry]),");
  lines.push(");");
  lines.push("");
  lines.push(
    "export const allCheatsheetMetas: CheatsheetMeta[] = cheatsheetEntries.map(",
  );
  lines.push("  (e) => e.meta,");
  lines.push(");");
  lines.push("");
  lines.push("export function getAllCheatsheetSlugs(): string[] {");
  lines.push("  return cheatsheetEntries.map((e) => e.meta.slug);");
  lines.push("}");
  lines.push("");
  lines.push(
    `// Count at generation time: cheatsheets=${cheatsheetSlugs.length}`,
  );

  return lines.join("\n");
}

async function main(): Promise<void> {
  const startTime = Date.now();

  // --- Discover meta.ts files ---
  const toolPaths = await fg("src/tools/*/meta.ts", { cwd: ROOT });
  const cheatsheetPaths = await fg("src/cheatsheets/*/meta.ts", {
    cwd: ROOT,
  });

  // Sort for deterministic output (git diff stays clean on re-generation)
  toolPaths.sort();
  cheatsheetPaths.sort();

  const toolSlugs = toolPaths.map(slugFromPath);
  const cheatsheetSlugs = cheatsheetPaths.map(slugFromPath);

  // --- Sanity checks (early-fail on unexpected structural changes) ---
  assertMinCount("tools", toolSlugs.length, 10);

  // --- Generate and write: tools-only registry ---
  const toolsContent = buildToolsRegistryContent(toolSlugs) + "\n";
  const toolsOutputDir = path.dirname(TOOLS_OUTPUT_FILE);
  if (!fs.existsSync(toolsOutputDir)) {
    fs.mkdirSync(toolsOutputDir, { recursive: true });
  }
  fs.writeFileSync(TOOLS_OUTPUT_FILE, toolsContent, "utf-8");

  // --- Generate and write: cheatsheets-only registry ---
  const cheatsheetsContent =
    buildCheatsheetRegistryContent(cheatsheetSlugs) + "\n";
  const cheatsheetsOutputDir = path.dirname(CHEATSHEETS_OUTPUT_FILE);
  if (!fs.existsSync(cheatsheetsOutputDir)) {
    fs.mkdirSync(cheatsheetsOutputDir, { recursive: true });
  }
  fs.writeFileSync(CHEATSHEETS_OUTPUT_FILE, cheatsheetsContent, "utf-8");

  const elapsed = Date.now() - startTime;
  console.log(
    `[generate-toolbox-registry] tools=${toolSlugs.length} cheatsheets=${cheatsheetSlugs.length} → ${TOOLS_OUTPUT_FILE}, ${CHEATSHEETS_OUTPUT_FILE} (${elapsed}ms)`,
  );
}

main().catch((err: unknown) => {
  console.error("[generate-toolbox-registry] Fatal error:", err);
  process.exit(1);
});
