/**
 * Prebuild script: Generate the 4-domain tiles registry from declared tile entries.
 *
 * This script generates:
 *   `src/tools/generated/tiles-registry.ts` — single registry spanning all 4 domains
 *
 * WHY a separate script (not merged into generate-toolbox-registry.ts):
 * - Independent deletion unit: if Phase 7 is reverted (6th failure), delete this file
 *   and remove the `generate:tiles-registry` entry from package.json scripts.
 *   No changes to generate-toolbox-registry.ts or its callers needed.
 * - Scope separation: toolbox-registry covers tools/cheatsheets per-slug meta discovery;
 *   tiles-registry covers the 4-domain tile declaration (distinct concern).
 *
 * TILE DECLARATION MODEL (Phase 7.3):
 * - Existing meta files (tools/cheatsheets/play/dictionary) are NOT touched.
 * - Tile-enabled entries are declared in `src/tools/_constants/tile-declarations.ts`.
 * - At Phase 7 time, 0 entries are declared (all meta files lack tile definitions).
 *   The codegen works correctly with 0 entries — empty registry is the expected output.
 * - Phase 8 implementors add entries to tile-declarations.ts when a tile is ready.
 *
 * OUTPUT:
 *   src/tools/generated/tiles-registry.ts (committed to git, regenerated on prebuild)
 *
 * DELETION UNIT (for 6th failure revert):
 *   1. Delete this file (scripts/generate-tiles-registry.ts)
 *   2. Delete scripts/__tests__/generate-tiles-registry.test.ts
 *   3. Delete src/tools/_constants/tile-declarations.ts
 *   4. Delete src/tools/generated/tiles-registry.ts
 *   5. Delete src/app/(new)/internal/tiles/page.tsx
 *   6. Remove `generate:tiles-registry` from package.json scripts
 *   7. Remove `generate:tiles-registry` call from prebuild/predev/pretest in package.json
 */

import fs from "node:fs";
import path from "node:path";

// TileDomain と TileRegistryEntry の SSoT は src/tools/_constants/tile-declarations.ts。
// scripts/ → src/ の方向の import は tsx 実行環境で可能であり、
// このファイル自身が dynamic import で src/ ファイルを参照していることがその証左。
// 静的 import type は型消去されるためランタイムに影響しない。
import type {
  TileDomain,
  TileRegistryEntry,
} from "../src/tools/_constants/tile-declarations";

// TileDomain を re-export して外部（テスト等）から参照できるようにする。
// 実体は src/tools/_constants/tile-declarations.ts にある（二重定義ではなく re-export）。
export type { TileDomain, TileRegistryEntry };

const ROOT = path.resolve(process.cwd());
const TILES_OUTPUT_FILE = path.join(
  ROOT,
  "src/tools/generated/tiles-registry.ts",
);
const TILE_DECLARATIONS_FILE = path.join(
  ROOT,
  "src/tools/_constants/tile-declarations.ts",
);

/**
 * Generate the TypeScript source content for src/tools/generated/tiles-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory (no file I/O).
 * This is the independently deletable export unit for T-3 (Phase 7.3).
 * If Phase 7 is reverted, delete this file along with the callers listed above.
 *
 * @param entries - tile registry entries (TileRegistryEntry = TileDefinition & { domain; slug })
 *   0 entries is valid at Phase 7 time.
 *   tileComponent フィールドはコンポーネント参照のため出力ファイルには書き出さない。
 *   出力には domain / slug / kind のシリアライズ可能なフィールドのみを含む。
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildTilesRegistryContent(
  entries: TileRegistryEntry[],
): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-tiles-registry.ts",
    " * Regenerate with: npm run generate:tiles-registry",
    " *",
    " * 4 系統横断タイルレジストリ（Phase 7.3）。",
    " * 宣言元: src/tools/_constants/tile-declarations.ts",
    " * Phase 8 で各コンテンツがタイル定義（TileDefinition & { domain; slug }）を",
    " * tile-declarations.ts の TILE_DECLARATIONS 配列に追加 → regenerate で自動反映される。",
    " * tileComponent は本ファイルには含まれない（関数参照のため serialization 不可）。",
    " * 実行時に tileComponent を使用するコードは tile-declarations.ts を直接 import する。",
    " */",
    "",
    'import type { TileRegistryEntry } from "@/tools/_constants/tile-declarations";',
    "",
    "/**",
    " * 4 系統横断タイルレジストリ（Phase 7.3）。",
    " * tools / cheatsheets / play / dictionary の全タイル化済エントリを収録する。",
    " * Phase 7 時点では全エントリ 0 件（タイル定義がまだ存在しないため）。",
    " *",
    " * domain / slug / kind のシリアライズ可能な 3 フィールドのみを収録する。",
    " * tileComponent（React コンポーネント参照）等は serialization 不可のため含まれない。",
    " * 実行時に tileComponent を使用するコードは tile-declarations.ts を直接 import する。",
    " */",
  ];

  // 型エイリアスを生成ファイルに埋め込む（型のみのエイリアス）
  const typeAlias =
    'type TileRegistrySerializedEntry = Pick<TileRegistryEntry, "domain" | "slug" | "kind">;';

  if (entries.length === 0) {
    // Empty array: Prettier formats as inline `[]`
    lines.push(typeAlias);
    lines.push(
      "export const tilesRegistry: TileRegistrySerializedEntry[] = [];",
    );
  } else {
    lines.push(typeAlias);
    lines.push("export const tilesRegistry: TileRegistrySerializedEntry[] = [");
    for (const entry of entries) {
      lines.push(
        `  { domain: "${entry.domain}", slug: "${entry.slug}", kind: "${entry.kind}" },`,
      );
    }
    lines.push("];");
  }
  lines.push("");
  lines.push(`// Count at generation time: tilesCount=${entries.length}`);

  return lines.join("\n");
}

async function main(): Promise<void> {
  const startTime = Date.now();

  // tile-declarations.ts から entries を読み込む
  // ファイルが存在しない場合は空配列で動作する（Phase 7 初期状態）
  let entries: TileRegistryEntry[] = [];
  if (fs.existsSync(TILE_DECLARATIONS_FILE)) {
    // dynamic import で tile-declarations.ts の宣言配列を読み込む。
    // TILE_DECLARATIONS の実体型は TileRegistryEntry[] = TileDefinition & { domain; slug }。
    // tileComponent（ComponentType）を含むため型アサーションが必要だが、
    // SSoT 型（TileRegistryEntry）を使用することで型の整合は tile-declarations.ts 側の
    // 型注釈 `TILE_DECLARATIONS: TileRegistryEntry[]` によってコンパイル時に保証される。
    const mod = (await import(TILE_DECLARATIONS_FILE)) as {
      TILE_DECLARATIONS?: TileRegistryEntry[];
    };
    if (mod.TILE_DECLARATIONS && Array.isArray(mod.TILE_DECLARATIONS)) {
      entries = mod.TILE_DECLARATIONS;
    }
  }

  // --- Generate and write: tiles registry ---
  const content = buildTilesRegistryContent(entries) + "\n";
  const outputDir = path.dirname(TILES_OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  fs.writeFileSync(TILES_OUTPUT_FILE, content, "utf-8");

  const elapsed = Date.now() - startTime;
  console.log(
    `[generate-tiles-registry] tilesCount=${entries.length} → ${TILES_OUTPUT_FILE} (${elapsed}ms)`,
  );
}

main().catch((err: unknown) => {
  console.error("[generate-tiles-registry] Fatal error:", err);
  process.exit(1);
});
