/**
 * Prebuild script: Generate the 4-domain tiles registry from declared tile entries.
 *
 * This script generates:
 *   `src/tools/generated/tiles-registry.ts` — single registry spanning all 4 domains
 *
 * WHY a separate script (not merged into generate-toolbox-registry.ts):
 * - Independent deletion unit: if Phase 7 is reverted (6th failure), delete this file
 *   and remove the `generate:tiles-registry` entry from package.json scripts.
 *   No changes to generate-toolbox-registry.ts or its callers needed.
 * - Scope separation: toolbox-registry covers tools/cheatsheets per-slug meta discovery;
 *   tiles-registry covers the 4-domain tile declaration (distinct concern).
 *
 * TILE DECLARATION MODEL (Phase 7.3):
 * - Existing meta files (tools/cheatsheets/play/dictionary) are NOT touched.
 * - Tile-enabled entries are declared in `src/tools/_constants/tile-declarations.ts`.
 * - At Phase 7 time, 0 entries are declared (all meta files lack tile definitions).
 *   The codegen works correctly with 0 entries — empty registry is the expected output.
 * - Phase 8 implementors add entries to tile-declarations.ts when a tile is ready.
 *
 * OUTPUT:
 *   src/tools/generated/tiles-registry.ts (committed to git, regenerated on prebuild)
 *
 * DELETION UNIT (for 6th failure revert):
 *   1. Delete this file (scripts/generate-tiles-registry.ts)
 *   2. Delete scripts/__tests__/generate-tiles-registry.test.ts
 *   3. Delete src/tools/_constants/tile-declarations.ts
 *   4. Delete src/tools/generated/tiles-registry.ts
 *   5. Delete src/app/(new)/internal/tiles/page.tsx
 *   6. Remove `generate:tiles-registry` from package.json scripts
 *   7. Remove `generate:tiles-registry` call from prebuild/predev/pretest in package.json
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(process.cwd());
const TILES_OUTPUT_FILE = path.join(
  ROOT,
  "src/tools/generated/tiles-registry.ts",
);
const TILE_DECLARATIONS_FILE = path.join(
  ROOT,
  "src/tools/_constants/tile-declarations.ts",
);

/**
 * 系統識別子の型（4 系統）。
 * tools / cheatsheets / play / dictionary の 4 値。
 */
export type TileDomain = "tools" | "cheatsheets" | "play" | "dictionary";

/**
 * tiles-registry 生成関数への入力型。
 * 各エントリは「系統識別子 + slug + kind（形態識別子）」を持つ。
 * TileDefinition の全フィールド（tileComponent 等）は実行時に tile-declarations.ts から参照する。
 * この入力型は codegen の単体テスト用に軽量な構造にしている。
 */
export interface TileRegistryInput {
  /** 系統識別子: 4 系統のいずれか */
  domain: TileDomain;
  /** コンテンツの slug（URL 用のケバブケース文字列） */
  slug: string;
  /** 形態識別子: Discriminated Union の discriminant（AP-I02 回避） */
  kind: "single" | "widget" | "multi";
}

/**
 * Generate the TypeScript source content for src/tools/generated/tiles-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory (no file I/O).
 * This is the independently deletable export unit for T-3 (Phase 7.3).
 * If Phase 7 is reverted, delete this file along with the callers listed above.
 *
 * @param entries - tile registry entries (0 entries is valid at Phase 7 time)
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildTilesRegistryContent(
  entries: TileRegistryInput[],
): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-tiles-registry.ts",
    " * Regenerate with: npm run generate:tiles-registry",
    " *",
    " * 4 系統横断タイルレジストリ（Phase 7.3）。",
    " * 宣言元: src/tools/_constants/tile-declarations.ts",
    " * Phase 8 で各コンテンツがタイル定義を埋めるたびに、",
    " * tile-declarations.ts にエントリを追加 → regenerate で自動反映される。",
    " */",
    "",
    'import type { TileRegistryEntry } from "@/tools/_constants/tile-declarations";',
    "",
    "/**",
    " * 4 系統横断タイルレジストリ（Phase 7.3）。",
    " * tools / cheatsheets / play / dictionary の全タイル化済エントリを収録する。",
    " * Phase 7 時点では全エントリ 0 件（タイル定義がまだ存在しないため）。",
    " */",
  ];

  if (entries.length === 0) {
    // Empty array: Prettier formats as inline `[]`
    lines.push("export const tilesRegistry: TileRegistryEntry[] = [];");
  } else {
    lines.push("export const tilesRegistry: TileRegistryEntry[] = [");
    for (const entry of entries) {
      lines.push(
        `  { domain: "${entry.domain}", slug: "${entry.slug}", kind: "${entry.kind}" },`,
      );
    }
    lines.push("];");
  }
  lines.push("");
  lines.push(`// Count at generation time: tilesCount=${entries.length}`);

  return lines.join("\n");
}

async function main(): Promise<void> {
  const startTime = Date.now();

  // tile-declarations.ts から entries を読み込む
  // ファイルが存在しない場合は空配列で動作する（Phase 7 初期状態）
  let entries: TileRegistryInput[] = [];
  if (fs.existsSync(TILE_DECLARATIONS_FILE)) {
    // dynamic import で tile-declarations.ts の宣言配列を読み込む
    const mod = (await import(TILE_DECLARATIONS_FILE)) as {
      TILE_DECLARATIONS?: TileRegistryInput[];
    };
    if (mod.TILE_DECLARATIONS && Array.isArray(mod.TILE_DECLARATIONS)) {
      entries = mod.TILE_DECLARATIONS;
    }
  }

  // --- Generate and write: tiles registry ---
  const content = buildTilesRegistryContent(entries) + "\n";
  const outputDir = path.dirname(TILES_OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  fs.writeFileSync(TILES_OUTPUT_FILE, content, "utf-8");

  const elapsed = Date.now() - startTime;
  console.log(
    `[generate-tiles-registry] tilesCount=${entries.length} → ${TILES_OUTPUT_FILE} (${elapsed}ms)`,
  );
}

main().catch((err: unknown) => {
  console.error("[generate-tiles-registry] Fatal error:", err);
  process.exit(1);
});
