/**
 * Prebuild script: Generate unified toolbox registry from individual meta.ts files.
 *
 * This script auto-discovers `meta.ts` files under `src/tools/` and `src/cheatsheets/`
 * and generates four files:
 *   1. `src/lib/toolbox/generated/toolbox-registry.ts`          — unified Tileable[] for toolbox
 *   2. `src/tools/generated/tools-registry.ts`                  — tools-only registry (replaces hand-written)
 *   3. `src/cheatsheets/generated/cheatsheets-registry.ts`      — cheatsheets-only registry (replaces hand-written)
 *   4. `src/lib/toolbox/generated/tile-definitions-registry.ts` — tile definitions (Phase 7.3)
 *
 * WHY codegen instead of hand-maintained central registry:
 * - Eliminates the class of bug where a developer adds `src/tools/new-tool/meta.ts`
 *   but forgets to register it in the registry.
 * - At 500+ entries scale, manual registration in a central file is error-prone.
 * - The `meta.ts` file IS the registration — no separate step needed.
 *
 * SCOPE:
 * - tools: `src/tools/{slug}/meta.ts` (named export `meta: ToolMeta`)
 * - cheatsheets: `src/cheatsheets/{slug}/meta.ts` (named export `meta: CheatsheetMeta`)
 * - play: NOT auto-discovered (no per-content meta.ts exists; handled by existing
 *         `src/play/registry.ts` which is imported directly in the generated file)
 * - tile definitions: `src/tools/{slug}/tile.ts`, `src/play/{games|quiz|fortune}/{slug}/tile.ts`
 *   (optional; only collected when the file exists — Phase 7.3)
 *   NOTE: cheatsheets / dictionary tile definitions are out of scope (Phase 9.2 / 9.3).
 *
 * CALLER COMPATIBILITY:
 * - `src/tools/registry.ts` re-exports from `src/tools/generated/tools-registry.ts`
 *   → callers (79 files) are unaffected; same export API (toolsBySlug, allToolMetas, getAllToolSlugs)
 * - `src/cheatsheets/registry.ts` re-exports from `src/cheatsheets/generated/cheatsheets-registry.ts`
 *   → callers (22 files) are unaffected; same export API (cheatsheetsBySlug, allCheatsheetMetas, getAllCheatsheetSlugs)
 *
 * OUTPUT files (all committed to git; lint/typecheck works without running prebuild):
 * - Regenerated on every prebuild/predev/pretest to stay in sync
 * - If manually edited, run `npm run generate:toolbox-registry` to revert.
 *   The git diff will show the unwanted edits, making them easy to detect and revert.
 */

import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import { allPlayContents } from "../src/play/registry.js";

const ROOT = path.resolve(process.cwd());
const OUTPUT_FILE = path.join(
  ROOT,
  "src/lib/toolbox/generated/toolbox-registry.ts",
);
const OUTPUT_DIR = path.dirname(OUTPUT_FILE);
const TOOLS_OUTPUT_FILE = path.join(
  ROOT,
  "src/tools/generated/tools-registry.ts",
);
const CHEATSHEETS_OUTPUT_FILE = path.join(
  ROOT,
  "src/cheatsheets/generated/cheatsheets-registry.ts",
);
const TILE_DEFINITIONS_OUTPUT_FILE = path.join(
  ROOT,
  "src/lib/toolbox/generated/tile-definitions-registry.ts",
);

/** Extract slug from path like "src/tools/{slug}/meta.ts" */
function slugFromPath(filePath: string): string {
  const parts = filePath.split("/");
  // parts = ["src", "tools", "{slug}", "meta.ts"] → index -2 is slug
  return parts[parts.length - 2];
}

/**
 * 件数のサニティチェック。
 * glob の誤設定や予期しないディレクトリ構造変化で件数が激減した場合に早期エラーを出す。
 */
function assertMinCount(kind: string, actual: number, min: number): void {
  if (actual < min) {
    throw new Error(
      `[generate-toolbox-registry] SANITY CHECK FAILED: ` +
        `Expected at least ${min} ${kind} meta.ts files, but found ${actual}. ` +
        `Check src/${kind}/ directory structure.`,
    );
  }
}

/**
 * Generate the TypeScript source content for tools/generated/tools-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory.
 * This replaces the hand-written src/tools/registry.ts entry list.
 * The generated file is re-exported by src/tools/registry.ts to preserve
 * caller compatibility (toolsBySlug, allToolMetas, getAllToolSlugs).
 *
 * @param toolSlugs - sorted list of tool slugs discovered from src/tools/{slug}/meta.ts
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildToolsRegistryContent(toolSlugs: string[]): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-toolbox-registry.ts",
    " * Regenerate with: npm run generate:toolbox-registry",
    " *",
    " * This file is re-exported by src/tools/registry.ts.",
    " * Callers should import from src/tools/registry.ts, not this file.",
    " */",
    "",
    'import type { ToolMeta, ToolDefinition } from "@/tools/types";',
    "",
    "// --- Tool imports (auto-discovered from src/tools/{slug}/meta.ts) ---",
  ];

  for (const slug of toolSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`import { meta as ${importName} } from "@/tools/${slug}/meta";`);
  }

  lines.push("");
  lines.push("const toolEntries: ToolDefinition[] = [");
  for (const slug of toolSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`  { meta: ${importName} },`);
  }
  lines.push("];");
  lines.push("");
  lines.push("// Indexed by slug for O(1) lookup");
  lines.push(
    "export const toolsBySlug: Map<string, ToolDefinition> = new Map(",
  );
  lines.push("  toolEntries.map((entry) => [entry.meta.slug, entry]),");
  lines.push(");");
  lines.push("");
  lines.push("// All tool metadata (no component code loaded)");
  lines.push(
    "export const allToolMetas: ToolMeta[] = toolEntries.map((e) => e.meta);",
  );
  lines.push("");
  lines.push("// Get all tool slugs");
  lines.push("export function getAllToolSlugs(): string[] {");
  lines.push("  return toolEntries.map((e) => e.meta.slug);");
  lines.push("}");
  lines.push("");
  lines.push(`// Count at generation time: tools=${toolSlugs.length}`);

  return lines.join("\n");
}

/**
 * Generate the TypeScript source content for cheatsheets/generated/cheatsheets-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory.
 * This replaces the hand-written src/cheatsheets/registry.ts entry list.
 * The generated file is re-exported by src/cheatsheets/registry.ts to preserve
 * caller compatibility (cheatsheetsBySlug, allCheatsheetMetas, getAllCheatsheetSlugs).
 *
 * @param cheatsheetSlugs - sorted list of cheatsheet slugs from src/cheatsheets/{slug}/meta.ts
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildCheatsheetRegistryContent(
  cheatsheetSlugs: string[],
): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-toolbox-registry.ts",
    " * Regenerate with: npm run generate:toolbox-registry",
    " *",
    " * This file is re-exported by src/cheatsheets/registry.ts.",
    " * Callers should import from src/cheatsheets/registry.ts, not this file.",
    " */",
    "",
    'import type { CheatsheetMeta, CheatsheetDefinition } from "@/cheatsheets/types";',
    "",
    "// --- Cheatsheet imports (auto-discovered from src/cheatsheets/{slug}/meta.ts) ---",
  ];

  for (const slug of cheatsheetSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(
      `import { meta as ${importName} } from "@/cheatsheets/${slug}/meta";`,
    );
  }

  lines.push("");
  lines.push("const cheatsheetEntries: CheatsheetDefinition[] = [");
  for (const slug of cheatsheetSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`  { meta: ${importName} },`);
  }
  lines.push("];");
  lines.push("");
  lines.push(
    "export const cheatsheetsBySlug: Map<string, CheatsheetDefinition> = new Map(",
  );
  lines.push("  cheatsheetEntries.map((entry) => [entry.meta.slug, entry]),");
  lines.push(");");
  lines.push("");
  lines.push(
    "export const allCheatsheetMetas: CheatsheetMeta[] = cheatsheetEntries.map(",
  );
  lines.push("  (e) => e.meta,");
  lines.push(");");
  lines.push("");
  lines.push("export function getAllCheatsheetSlugs(): string[] {");
  lines.push("  return cheatsheetEntries.map((e) => e.meta.slug);");
  lines.push("}");
  lines.push("");
  lines.push(
    `// Count at generation time: cheatsheets=${cheatsheetSlugs.length}`,
  );

  return lines.join("\n");
}

/**
 * Tile definition entry — collected from optional `tile.ts` files under content directories.
 *
 * Used as the input type for buildTileDefinitionsRegistryContent().
 */
export interface TileDefinitionEntry {
  /** Content slug (matches the slug in meta.ts for the same directory). */
  slug: string;
  /**
   * Source path of the tile.ts file relative to the project root.
   * Used to generate the correct @/ import path in the output file.
   * Examples:
   *   "src/tools/json-formatter/tile.ts"
   *   "src/play/games/irodori/tile.ts"
   *   "src/play/quiz/kanji-level/tile.ts"
   */
  contentPath: string;
}

/**
 * Convert a content path like "src/tools/json-formatter/tile.ts"
 * to an @/ alias import path like "@/tools/json-formatter/tile".
 */
function contentPathToImportPath(contentPath: string): string {
  // Remove leading "src/" and trailing ".ts" extension
  const withoutSrc = contentPath.replace(/^src\//, "");
  const withoutExt = withoutSrc.replace(/\.ts$/, "");
  return `@/${withoutExt}`;
}

/**
 * Generate the TypeScript source content for tile-definitions-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory
 * without touching the filesystem.
 *
 * Phase 7.3 (CRIT-5): tile definitions may be 0 at generation time.
 * No assertMinCount check is added here — Phase 8 will add it once the first
 * tile implementation exists.
 *
 * @param tileEntries - sorted list of tile definition entries discovered from tile.ts files
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildTileDefinitionsRegistryContent(
  tileEntries: TileDefinitionEntry[],
): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-toolbox-registry.ts",
    " * Regenerate with: npm run generate:toolbox-registry",
    " *",
    " * If you find a manual edit here, run `npm run generate:toolbox-registry`",
    " * to restore. The git diff makes unintended edits easy to detect and revert.",
    " *",
    " * This file collects optional tile definitions from content directories.",
    " * Each content's `tile.ts` exports a `tileDef: TileDefinition` const.",
    " * The public API is exposed via src/lib/toolbox/registry.ts — callers should",
    " * never import this file directly.",
    " *",
    " * SCOPE (Phase 7.3):",
    " *   - src/tools/{slug}/tile.ts",
    " *   - src/play/games/{slug}/tile.ts",
    " *   - src/play/quiz/{slug}/tile.ts",
    " *   - src/play/fortune/{slug}/tile.ts",
    " * OUT OF SCOPE: cheatsheets / dictionary (Phase 9.2 / 9.3).",
    " *",
    " * COUNT at generation time is 0 until Phase 8 adds individual tile implementations.",
    " */",
    "",
    'import type { TileDefinition } from "../tile-types";',
    "",
  ];

  if (tileEntries.length === 0) {
    lines.push(
      "// No tile.ts files found yet. Phase 8 will add individual tile implementations.",
    );
    lines.push("");
    lines.push("export const allTileDefinitions: TileDefinition[] = [];");
  } else {
    lines.push(
      "// --- Tile definition imports (auto-discovered from tile.ts files) ---",
    );
    for (const entry of tileEntries) {
      const importName = `tile_${entry.slug.replace(/-/g, "_")}`;
      const importPath = contentPathToImportPath(entry.contentPath);
      lines.push(`import { tileDef as ${importName} } from "${importPath}";`);
    }

    lines.push("");
    lines.push("export const allTileDefinitions: TileDefinition[] = [");
    for (const entry of tileEntries) {
      const importName = `tile_${entry.slug.replace(/-/g, "_")}`;
      lines.push(`  ${importName},`);
    }
    lines.push("];");
  }

  lines.push("");
  lines.push(`// Count at generation time: tiles=${tileEntries.length}`);

  return lines.join("\n");
}

/**
 * Generate the TypeScript source content for toolbox-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory
 * without touching the filesystem (scripts/__tests__/generate-toolbox-registry.test.ts).
 *
 * @param toolSlugs - sorted list of tool slugs discovered from src/tools/{slug}/meta.ts
 * @param playCount - count of allPlayContents at generation time (for the comment)
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildRegistryContent(
  toolSlugs: string[],
  playCount: number,
): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-toolbox-registry.ts",
    " * Regenerate with: npm run generate:toolbox-registry",
    " *",
    " * If you find a manual edit here, run `npm run generate:toolbox-registry`",
    " * to restore. The git diff makes unintended edits easy to detect and revert.",
    " *",
    " * This file merges all tool / play entries into a unified",
    " * Tileable[] array.  The public API (getAllTileables, getTileableBySlug)",
    " * is exposed via src/lib/toolbox/registry.ts which",
    " * imports from here — callers should never import this file directly.",
    " *",
    " * TOOLS are auto-discovered from meta.ts files.",
    " * PLAY is imported from the existing src/play/registry.ts because play",
    " * content does not follow the per-slug meta.ts convention.",
    " */",
    "",
    'import type { Tileable } from "../types";',
    'import { toTileable } from "../types";',
    "",
    "// --- Tool imports (auto-discovered from src/tools/{slug}/meta.ts) ---",
  ];

  // Tool imports
  for (const slug of toolSlugs) {
    const importName = `tool_${slug.replace(/-/g, "_")}`;
    lines.push(`import { meta as ${importName} } from "@/tools/${slug}/meta";`);
  }

  lines.push("");
  lines.push(
    "// --- Play import (not auto-discovered; uses existing registry) ---",
  );
  lines.push('import { allPlayContents } from "@/play/registry";');
  lines.push("");
  lines.push("// --- Unified Tileable arrays ---");
  lines.push("");
  lines.push(
    "/** All tool Tileables (auto-discovered from src/tools/{slug}/meta.ts). */",
  );
  lines.push("export const toolTileables: Tileable[] = [");
  for (const slug of toolSlugs) {
    const importName = `tool_${slug.replace(/-/g, "_")}`;
    lines.push(`  toTileable(${importName}, "tool"),`);
  }
  lines.push("];");
  lines.push("");
  lines.push(
    "/** All play Tileables (sourced from existing src/play/registry.ts). */",
  );
  lines.push("export const playTileables: Tileable[] = [");
  lines.push('  ...allPlayContents.map((meta) => toTileable(meta, "play")),');
  lines.push("];");
  lines.push("");
  lines.push(
    `// Counts at generation time: tools=${toolSlugs.length}, play=${playCount} (from src/play/registry.ts)`,
  );

  return lines.join("\n");
}

async function main(): Promise<void> {
  const startTime = Date.now();

  // --- Discover meta.ts files ---
  const toolPaths = await fg("src/tools/*/meta.ts", { cwd: ROOT });
  const cheatsheetPaths = await fg("src/cheatsheets/*/meta.ts", {
    cwd: ROOT,
  });

  // Sort for deterministic output (git diff stays clean on re-generation)
  toolPaths.sort();
  cheatsheetPaths.sort();

  const toolSlugs = toolPaths.map(slugFromPath);
  const cheatsheetSlugs = cheatsheetPaths.map(slugFromPath);
  const playCount = allPlayContents.length;

  // --- Sanity checks (early-fail on unexpected structural changes) ---
  assertMinCount("tools", toolSlugs.length, 10);

  // --- Generate and write: toolbox unified registry ---
  const toolboxContent = buildRegistryContent(toolSlugs, playCount) + "\n";
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
  fs.writeFileSync(OUTPUT_FILE, toolboxContent, "utf-8");

  // --- Generate and write: tools-only registry ---
  const toolsContent = buildToolsRegistryContent(toolSlugs) + "\n";
  const toolsOutputDir = path.dirname(TOOLS_OUTPUT_FILE);
  if (!fs.existsSync(toolsOutputDir)) {
    fs.mkdirSync(toolsOutputDir, { recursive: true });
  }
  fs.writeFileSync(TOOLS_OUTPUT_FILE, toolsContent, "utf-8");

  // --- Generate and write: cheatsheets-only registry ---
  const cheatsheetsContent =
    buildCheatsheetRegistryContent(cheatsheetSlugs) + "\n";
  const cheatsheetsOutputDir = path.dirname(CHEATSHEETS_OUTPUT_FILE);
  if (!fs.existsSync(cheatsheetsOutputDir)) {
    fs.mkdirSync(cheatsheetsOutputDir, { recursive: true });
  }
  fs.writeFileSync(CHEATSHEETS_OUTPUT_FILE, cheatsheetsContent, "utf-8");

  // --- Discover tile.ts files (Phase 7.3) ---
  // Collect optional tile definitions from tools and play content directories.
  // cheatsheets / dictionary are out of scope (Phase 9.2 / 9.3).
  // Play content without per-slug directories (daily, shared registries) is
  // naturally excluded because no {slug}/tile.ts file path exists for them.
  const tilePaths = await fg(
    [
      "src/tools/*/tile.ts",
      "src/play/games/*/tile.ts",
      "src/play/quiz/*/tile.ts",
      "src/play/fortune/*/tile.ts",
    ],
    { cwd: ROOT },
  );

  // Sort for deterministic output
  tilePaths.sort();

  const tileEntries: TileDefinitionEntry[] = tilePaths.map((filePath) => ({
    slug: slugFromPath(filePath),
    contentPath: filePath,
  }));

  // --- Generate and write: tile definitions registry ---
  // NOTE: 0 entries is valid at Phase 7.3 completion. No assertMinCount here (CRIT-5).
  const tileDefinitionsContent =
    buildTileDefinitionsRegistryContent(tileEntries) + "\n";
  const tileDefinitionsOutputDir = path.dirname(TILE_DEFINITIONS_OUTPUT_FILE);
  if (!fs.existsSync(tileDefinitionsOutputDir)) {
    fs.mkdirSync(tileDefinitionsOutputDir, { recursive: true });
  }
  fs.writeFileSync(
    TILE_DEFINITIONS_OUTPUT_FILE,
    tileDefinitionsContent,
    "utf-8",
  );

  const elapsed = Date.now() - startTime;
  console.log(
    `[generate-toolbox-registry] tools=${toolSlugs.length} play=${playCount} tiles=${tileEntries.length} → ${OUTPUT_FILE}, ${TOOLS_OUTPUT_FILE}, ${CHEATSHEETS_OUTPUT_FILE}, ${TILE_DEFINITIONS_OUTPUT_FILE} (${elapsed}ms)`,
  );
}

main().catch((err: unknown) => {
  console.error("[generate-toolbox-registry] Fatal error:", err);
  process.exit(1);
});
