/**
 * Prebuild script: Generate the tools registry from individual meta.ts files.
 *
 * This script auto-discovers `meta.ts` files under `src/tools/` and generates:
 *   `src/tools/generated/tools-registry.ts` — tools-only registry (replaces hand-written)
 *
 * WHY codegen instead of hand-maintained central registry:
 * - Eliminates the class of bug where a developer adds `src/tools/new-tool/meta.ts`
 *   but forgets to register it in the registry.
 * - At 500+ entries scale, manual registration in a central file is error-prone.
 * - The `meta.ts` file IS the registration — no separate step needed.
 *
 * SCOPE:
 * - tools: `src/tools/{slug}/meta.ts` (named export `meta: ToolMeta`)
 *
 * NOTE: cheatsheets generation was removed in cycle-243 (B-349) when the
 * cheatsheet feature was retired and its content migrated to blog articles.
 *
 * CALLER COMPATIBILITY:
 * - `src/tools/registry.ts` re-exports from `src/tools/generated/tools-registry.ts`
 *   → callers (79 files) are unaffected; same export API (toolsBySlug, allToolMetas, getAllToolSlugs)
 *
 * OUTPUT files (all committed to git; lint/typecheck works without running prebuild):
 * - Regenerated on every prebuild/predev/pretest to stay in sync
 * - If manually edited, run `npm run generate:toolbox-registry` to revert.
 *   The git diff will show the unwanted edits, making them easy to detect and revert.
 */

import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";

const ROOT = path.resolve(process.cwd());
const TOOLS_OUTPUT_FILE = path.join(
  ROOT,
  "src/tools/generated/tools-registry.ts",
);

/** Extract slug from path like "src/tools/{slug}/meta.ts" */
function slugFromPath(filePath: string): string {
  const parts = filePath.split("/");
  // parts = ["src", "tools", "{slug}", "meta.ts"] → index -2 is slug
  return parts[parts.length - 2];
}

/**
 * 件数のサニティチェック。
 * glob の誤設定や予期しないディレクトリ構造変化で件数が激減した場合に早期エラーを出す。
 */
function assertMinCount(kind: string, actual: number, min: number): void {
  if (actual < min) {
    throw new Error(
      `[generate-toolbox-registry] SANITY CHECK FAILED: ` +
        `Expected at least ${min} ${kind} meta.ts files, but found ${actual}. ` +
        `Check src/${kind}/ directory structure.`,
    );
  }
}

/**
 * Generate the TypeScript source content for tools/generated/tools-registry.ts.
 *
 * Exported as a pure function so it can be unit-tested in-memory.
 * This replaces the hand-written src/tools/registry.ts entry list.
 * The generated file is re-exported by src/tools/registry.ts to preserve
 * caller compatibility (toolsBySlug, allToolMetas, getAllToolSlugs).
 *
 * @param toolSlugs - sorted list of tool slugs discovered from src/tools/{slug}/meta.ts
 * @returns TypeScript source string (without trailing newline — caller adds it)
 */
export function buildToolsRegistryContent(toolSlugs: string[]): string {
  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.",
    " *",
    " * Generated by: scripts/generate-toolbox-registry.ts",
    " * Regenerate with: npm run generate:toolbox-registry",
    " *",
    " * This file is re-exported by src/tools/registry.ts.",
    " * Callers should import from src/tools/registry.ts, not this file.",
    " */",
    "",
    'import type { ToolMeta, ToolDefinition } from "@/tools/types";',
    "",
    "// --- Tool imports (auto-discovered from src/tools/{slug}/meta.ts) ---",
  ];

  for (const slug of toolSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`import { meta as ${importName} } from "@/tools/${slug}/meta";`);
  }

  lines.push("");
  lines.push("const toolEntries: ToolDefinition[] = [");
  for (const slug of toolSlugs) {
    const importName = slug.replace(/-/g, "_");
    lines.push(`  { meta: ${importName} },`);
  }
  lines.push("];");
  lines.push("");
  lines.push("// Indexed by slug for O(1) lookup");
  lines.push(
    "export const toolsBySlug: Map<string, ToolDefinition> = new Map(",
  );
  lines.push("  toolEntries.map((entry) => [entry.meta.slug, entry]),");
  lines.push(");");
  lines.push("");
  lines.push("// All tool metadata (no component code loaded)");
  lines.push(
    "export const allToolMetas: ToolMeta[] = toolEntries.map((e) => e.meta);",
  );
  lines.push("");
  lines.push("// Get all tool slugs");
  lines.push("export function getAllToolSlugs(): string[] {");
  lines.push("  return toolEntries.map((e) => e.meta.slug);");
  lines.push("}");
  lines.push("");
  lines.push(`// Count at generation time: tools=${toolSlugs.length}`);

  return lines.join("\n");
}

async function main(): Promise<void> {
  const startTime = Date.now();

  // --- Discover meta.ts files ---
  const toolPaths = await fg("src/tools/*/meta.ts", { cwd: ROOT });

  // Sort for deterministic output (git diff stays clean on re-generation)
  toolPaths.sort();

  const toolSlugs = toolPaths.map(slugFromPath);

  // --- Sanity checks (early-fail on unexpected structural changes) ---
  assertMinCount("tools", toolSlugs.length, 10);

  // --- Generate and write: tools-only registry ---
  const toolsContent = buildToolsRegistryContent(toolSlugs) + "\n";
  const toolsOutputDir = path.dirname(TOOLS_OUTPUT_FILE);
  if (!fs.existsSync(toolsOutputDir)) {
    fs.mkdirSync(toolsOutputDir, { recursive: true });
  }
  fs.writeFileSync(TOOLS_OUTPUT_FILE, toolsContent, "utf-8");

  const elapsed = Date.now() - startTime;
  console.log(
    `[generate-toolbox-registry] tools=${toolSlugs.length} → ${TOOLS_OUTPUT_FILE} (${elapsed}ms)`,
  );
}

main().catch((err: unknown) => {
  console.error("[generate-toolbox-registry] Fatal error:", err);
  process.exit(1);
});
