/**
 * Thin re-export from the auto-generated registry.
 *
 * The source of truth is src/tools/generated/tools-registry.ts,
 * which is regenerated by: npm run generate:toolbox-registry
 *
 * Do NOT add manual imports here. Add a meta.ts file under
 * src/tools/{slug}/ and run generate:toolbox-registry instead.
 */
export {
  toolsBySlug,
  allToolMetas,
  getAllToolSlugs,
} from "./generated/tools-registry";
